; Listing generated by Microsoft (R) Optimizing Compiler Version 19.13.26132.0 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Solo\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
